### ISSUE TITLE
translation and grammar issues

### ISSUE THREAD

**Issue by TranslationIssue** [DiscordLaCommune/politiscales#11]
"Changes in individual way of life" would better translate to "changes in an individual's way of life"
"Research produced by my country should not be available to others" should specify "other countries" at the end of this sentence.
"It is necessary to implement assemblies to ration our productions to the consumers according to their needs": "productions" should be singular.
"GMO should be forbidden outside research and medical purposes": "GMO" should be plural.
Change "Labor market enslaves workers" to "The labor market enslave workers."
"If two countries have similar economies, social systems and environmental norms, then the free market between has no negative impact": the last clause should be "then the free market between them has no negative impact."
"It is a small group that consciously and secretlycontrols the world" needs a space between "secretly" and "controls."
"In some specific conditions, death penalty is justified" needs a "the" before "death."
"We must always militate in strict compliance with the law": not so much a translation issue, but i recommend that a different word be used than "militate", or even just use the phrase "prepare for war" instead.
"It is necessary to remove reglementation in the labour legislation to encourage firms to hire": in English we use "regulation." "Reglementation" is not a word in English. also the "the" before "labour" is not needed.
"Nowadays an employee is free of their choices when signing a contract with their future employer": please change this sentence because it's really difficult to read. Perhaps "Nowadays employees are free to choose when signing a contract with their future employer"?
"Justice should always take into consideration the context and the past of a condemned and adapt their penalty accordingly": replace "a" with"the."
"Prisons should be suppressed": perhaps "should no longer exist" in place of "be suppressed"?
"Maintaining a powerful economic growth should be an objective for the government": it make smore sense to say "Maintaining strong economic growth."

**Comment by ManoIzquierda** [comment]
Thanks a lot! I will add your corrections in the test.
Concerning "militate", we made a mistake with translation. The French word is "militer" which is more or less "act as an activist". Nothing related with war. Do you have any suggestions? Maybe "Regardless of the matter at stake, activists should always respect the law." or "No matter what's at stake, activists should always respect the law."?

**Comment by TranslationIssue** [comment]
You're welcome for the translation assistance and thank you for the response.
I would suggest that "Activists must always act in strict accordance with the law" since it's closer to the original translation.

**Comment by TerribleNews** [comment]
> 	"qj0": "Prisons should should no longer exist.",

Could could you remove one of the "shoulds" in this? (*;

**Comment by ManoIzquierda** [comment]
Thanks to both of you :)
